"""empty message

Revision ID: 41421a4d3b76
Revises: ad2f6bc89dd6
Create Date: 2024-01-11 13:48:05.066191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41421a4d3b76'
down_revision = 'ad2f6bc89dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('toys', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_table')
    # ### end Alembic commands ###
