"""empty message

Revision ID: ad2f6bc89dd6
Revises: cc67c4694821
Create Date: 2024-01-11 13:44:47.571536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2f6bc89dd6'
down_revision = 'cc67c4694821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy_table', schema=None) as batch_op:
        batch_op.drop_column('user')

    # ### end Alembic commands ###
