"""add name column

Revision ID: cc67c4694821
Revises: 09167b23038c
Create Date: 2024-01-11 12:22:37.624214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc67c4694821'
down_revision = '09167b23038c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toy_table', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
